apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "isplitapp.fullname" . }}
  labels:
    {{- include "isplitapp.labels" . | nindent 4 }}
spec:

  selector:
    matchLabels:
      {{- include "isplitapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        isa.io/export_logs: "true"
      labels:
        {{- include "isplitapp.labels" . | nindent 8 }}
    spec:

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:

        - name: nginx
          image: nginx:alpine
          ports: 
            - containerPort: {{ .Values.service.nginxPort }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-log
              mountPath: /var/log/nginx
            # - name: nginx-static
            #   mountPath: /var/www/html
          resources:
            requests:
              memory: "20Mi"


        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "ilaverlin/isplitapp-full:{{ include "isplitapp.tag" . }}"
          ports:
            - name: api
              containerPort: {{ .Values.service.apiPort }}
              protocol: TCP

          env:
            - name: "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE"
              value: "false"
            {{ if eq .Values.global.deployEnv "dev" -}}
            - name:  Logging__LogLevel__Default
              value: "Debug"
            - name: Logging__LogLevel__Microsoft.AspNetCore.HttpLogging
              value: "Debug"
            {{- end }}
            - name:  ASPNETCORE_ENVIRONMENT
              value: {{ .Values.global.deployEnv }}
            - name: ConnectionStrings__isplitapp
              valueFrom:
                secretKeyRef:
                  name: {{ include "isplitapp.fullname" . }}
                  key: isaPgUrl
            - name: Vapid__Subject
              valueFrom:
                secretKeyRef:
                  name: {{ include "isplitapp.fullname" . }}
                  key: vapidSubject                  
            - name: Vapid__PublicKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "isplitapp.fullname" . }}
                  key: vapidPublicKey
            - name: Vapid__PrivateKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "isplitapp.fullname" . }}
                  key: vapidPrivateKey


          volumeMounts:
            - name: fbkey
              mountPath: /app/secret

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "isplitapp.fullname" . }}
        - name: nginx-log
          hostPath:
            path: {{ .Values.global.storageRoot }}/persist/nginx-isa/log
            type: DirectoryOrCreate
        - name: fbkey
          configMap:
            name: fbkey
        # - name: nginx-static
        #   hostPath:
        #     path: {{ .Values.global.storageRoot }}/persist/wwwroot
        #     type: Directory
