apiVersion: v1
kind: Secret
metadata:
  name: {{ include "isplitapp.fullname" . }}
type: Opaque
data:
  isaPgUrl: {{ .Values.global.isaPgUrl | b64enc | quote }}
  vapidPublicKey: {{ .Values.global.vapidPublicKey | b64enc | quote }}
  vapidPrivateKey: {{ .Values.global.vapidPrivateKey | b64enc | quote }}
  vapidSubject: {{ .Values.global.vapidSubject | b64enc | quote }}