apiVersion: v1
kind: Service
metadata:
  name: {{ include "isplitapp.fullname" . }}
  labels:
    {{- include "isplitapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.nginxPort }}
      targetPort: {{ .Values.service.nginxPort }}
      protocol: TCP
      name: nginx
  selector:
    {{- include "isplitapp.selectorLabels" . | nindent 4 }}
