# Grafana pod deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: 'IfNotPresent'
          env:
            # - name: GF_DATABASE_URL
            #   value: sqlite3:///var/lib/grafana/grafana.db?cache=shared&mode=rwc&_journal_mode=WAL
            - name: GF_DATABASE_TYPE
              value: "postgres"
            - name: GF_DATABASE_HOST
              value: "pg-server.watch-backend:5432"
            - name: GF_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_USER
            - name: GF_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_PASS  

            - name: GF_INSTALL_PLUGINS
              value: "grafana-worldmap-panel"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_USER
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_PASS
          volumeMounts:
            - name: grafana-config
              mountPath: /etc/grafana
            - name: grafana-data
              mountPath: /var/lib/grafana
          securityContext:
            runAsUser: 0
            privileged: true
          resources:
            requests:
               memory: "200Mi"

      initContainers:
        - name: wait-postrges
          image: postgres:alpine
          command: ['sh', '-c', "until pg_isready -h pg-server.watch-backend -p 5432; do  echo waiting for pg-server.watch-backend; sleep 5; done"]

      volumes:
        - name: grafana-config
          hostPath:
            path: /shared-data/configs/grafana
            type: Directory
        - name: grafana-data
          hostPath:
            path: /shared-data/persist/grafana
            type: DirectoryOrCreate
---

# service
#
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
      name: grafana-port
  type: NodePort
