apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-ui
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-ui
  template:
    metadata:
      labels:
        app: kafka-ui
    spec:
      containers:
        - name: kafka-ui
          image: provectuslabs/kafka-ui
          ports:
            - containerPort: 8080
          imagePullPolicy: 'IfNotPresent'
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: kuber-kafka
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: kafka.watch-backend:9092 
          resources: 
            requests:
              memory: "100Mi"
---

# service
#
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: monitoring
spec:
  selector:
    app: kafka-ui
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888
      name: kafka-ui-port
  type: NodePort