# open telemetry collector pod deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector:latest
          command:
            - "/otelcol"
            - "--config=/etc/otel/config.yaml"
          ports:
            - containerPort: 4317
            - containerPort: 8889
            - containerPort: 8888
            - containerPort: 9411
          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "150Mi"
              cpu: "0.5"
          securityContext:
            runAsUser: 1001
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
      volumes:
        - name: otel-config
          hostPath:
            path: /shared-data/configs/otel
            type: Directory
---

# service
#
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  selector:
    app: otel-collector
  ports:
  - name: grps-receiver
    protocol: TCP
    port: 4317
  - name: zipkin-receiver
    protocol: TCP
    port: 9411
  - name: prom-metrics
    port: 8889
  - name: self-metrics
    port: 8888