# seq pod deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seq
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seq
  template:
    metadata:
      labels:
        app: seq
    spec:
      containers:
        - name: seq
          image: datalust/seq
          ports:
            - containerPort: 5341
            - containerPort: 80
          imagePullPolicy: 'IfNotPresent'
          env:
            - name: ACCEPT_EULA 
              value: "Y"
          volumeMounts:
            - name: seq-data
              mountPath: /data
          resources:
            limits:
              memory: "200Mi"
          #     cpu: "250m"
      volumes:
        - name: seq-data
          hostPath:
            path: /shared-data/persist/seq
            type: DirectoryOrCreate
---

# service
#
apiVersion: v1
kind: Service
metadata:
  name: seq
  namespace: monitoring
spec:
  selector:
    app: seq
  ports:
  - name: seq-port
    protocol: TCP
    port: 5341

---
apiVersion: v1
kind: Service
metadata:
  name: seq-ui
  namespace: monitoring
spec:
  selector:
    app: seq
  ports:
  - name: seq-ui-port
    protocol: TCP
    port: 80
    nodePort: 30801
  type: NodePort