# zipkin pod deployment
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zipkin
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim:latest
          ports:
            - containerPort: 9411
          imagePullPolicy: 'IfNotPresent'
          resources:
            limits:
              memory: "200Mi"

---

# service
#
apiVersion: v1
kind: Service
metadata:
  name: zipkin
  namespace: monitoring
spec:
  selector:
    app: zipkin
  ports:
  - name: zipkin-port
    protocol: TCP
    port: 9411
    nodePort: 30941
  type: NodePort