apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watch-yas.fullname" . }}-bot
  labels:
    {{- include "watch-yas-bot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.yasBot.replicaCount }}
  selector:
    matchLabels:
      {{- include "watch-yas-bot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watch-yas-bot.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "watch-yas.fullname" . }}-bot
          image: {{ .Values.yasBot.image.repository }}:{{ .Values.yasBot.image.tag | default "latest" }}
          env:
            - name: "DOTNET_HOSTBUILDER__RELOADCONFIGONCHANGE"
              value: "false"
            - name: Serilog__WriteTo__0__Args__uri
              value: {{ .Values.lokiUrl }}
            - name: BotConfiguration__OpenTelemetryCollectorUrl
              value: {{ include "otelUrlWithHttp" . }}
            - name: BotConfiguration__BaseReaderApiUrl
              value: http://{{ include "watch-yas.fullname" . }}-restapi:{{ .Values.yasRestapi.nginxPort }}/yas-api/

            - name: BotConfiguration__BotApiKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-yas.fullname" . }}
                  key: telegramBotApiToken
            - name: KafkaConfiguration__BootstrapServers
              value: {{ .Values.kafka.broker }}
            - name: KafkaConfiguration__Topic
              value: {{ .Values.kafka.topic }}
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            {{- toYaml .Values.yasBot.resources | nindent 12 }}