apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watch-yas.fullname" . }}
type: Opaque
data:
  pgUrl: {{ .Values.global.pgUrl | b64enc | quote }}
  telegramBotApiToken: {{ .Values.global.TelegramBotApiToken | b64enc | quote }}