apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "otel-collector.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-collector.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - "/otelcol"
            - "--config=/etc/otel/config.yaml"
          ports:
            - containerPort: {{ .Values.ports.prometheusExporter }}
            - containerPort: {{ .Values.ports.zipkinReceiver }}
            - containerPort: {{ .Values.ports.grpcReceiver }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
      volumes:
        - name: otel-config
          configMap:
            name: {{ include "otel-collector.fullname" . }}
