apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.prometheusExporter | quote }}
spec:
  selector:
    {{- include "otel-collector.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.global.deployEnv "dev" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ .Values.ports.prometheusExporter }}
      protocol: TCP
      name: prometheus
    - port: {{ .Values.ports.grpcReceiver }}
      {{- if eq .Values.global.deployEnv "dev" }}
      nodePort: {{ .Values.ports.grpcReceiverNodePort }}
      {{- end }}    
      protocol: TCP
      name: grpc
    - port: {{ .Values.ports.zipkinReceiver }}
      protocol: TCP
      name: zipkin

    - port: {{ .Values.ports.otelHttpPort }}
      protocol: TCP
      name: otel-http

