# Install acme.sh container
#
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: ingress
  name: acme-sh
  labels:
    app: acme-sh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acme-sh
  template:
    metadata:
      labels:
        app: acme-sh
    spec:
      containers:
        - name: acme-sh
          image: neilpang/acme.sh
          args:
            - daemon
          env:
            - name: Namecom_Username
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: NAMECOM_USER 
            - name: Namecom_Token 
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: NAMECOM_TOKEN
            - name: TELEGRAM_BOT_APITOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: TELEGRAM_YAS_BOT_KEY
            - name: TELEGRAM_BOT_CHATID
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: TELEGRAM_CHAT_ID
          resources:
            limits:
              memory: "20Mi"
              cpu: "0.1"
          volumeMounts:
            - mountPath: "/acmeout"
              name: acme-out
            - mountPath: "/acme.sh"
              name: acme-root

      volumes:
        - name: acme-out
          hostPath:
            path: /shared-data/persist/ssl
            type: DirectoryOrCreate
        - name: acme-root
          hostPath:
            path: /shared-data/persist/acme.sh
            type: DirectoryOrCreate