apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: ingress
  name: traefik
  labels:
    app: traefik
    app.kubernetes.io/name: traefik
spec:
  selector:
    matchLabels:
      app: traefik
      app.kubernetes.io/name: traefik
  template:
    metadata:
      labels:
        app: traefik
        app.kubernetes.io/name: traefik
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:latest
          args:
            - --api.insecure
            # - --accesslog
            # - --log.filePath=/logs/debug.log
            # - --log.level=DEBUG
            - --entrypoints.web.Address=:80
            - --entrypoints.websecure.Address=:443
            - --entrypoints.web.http.redirections.entryPoint.to=websecure
            - --entrypoints.web.http.redirections.entryPoint.scheme=https
            - --entrypoints.web.http.redirections.entrypoint.permanent=true

            - --providers.kubernetescrd=true
            - --providers.kubernetesingress=true

            - --serverstransport.insecureskipverify=true

            - --ping=true
            - --metrics.prometheus=true
            
          ports:
            - name: web
              containerPort: 80
              hostPort: 80
            - name: websecure
              containerPort: 443
              hostPort: 443
            - name: admin
              containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - mountPath: /logs
              name: tr-logs
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            failureThreshold: 1
            httpGet:
              path: /ping
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          securityContext:
            allowPrivilegeEscalation: true
            capabilities:
              drop:
              - ALL
              add:
              - NET_BIND_SERVICE
          resources:
            requests:
              memory: "100Mi"

      volumes:
        - name: tr-logs
          hostPath:
            path: /shared-data/logs/traefik
            type: DirectoryOrCreate
