# setup Nodeport
#
kind: Service
apiVersion: v1
metadata:
  name: traefik-nodeport
  namespace: ingress
spec:
  selector:
    app: traefik
  ports:
    - protocol: TCP
      port: 80
      name: web
      nodePort: 30800
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443
      name: secureweb
    - protocol: TCP
      port: 8080
      nodePort: 30808
      name: admin
  type: NodePort