# setup service for prometheus discovery
#
kind: Service
apiVersion: v1
metadata:
  name: traefik
  namespace: ingress
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '8080'
spec:
  selector:
    app: traefik
   # app.kubernetes.io/component: traefik
    app.kubernetes.io/name: traefik
  ports:
    - protocol: TCP
      port: 8080
      name: admin
