{
 "title": "Requests",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"traefik\"}"
    }
   ]
  },
  {
   "title": "Top 5 all return code",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{code!=\"200\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{protocol=\"http\"}) / sum(traefik_entrypoint_requests_total{protocol=\"http\"}) * 1000"
    }
   ]
  },
  {
   "title": "Access to services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"watch-backend-watch-api-micro-88@kubernetescrd|watch-backend-watch-api-mono-88@kubernetescrd\"}[1m])*60) by (service)",
     "legendFormat": "{{service}} "
    }
   ]
  },
  {
   "title": "Total requests (micro + mono)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"watch-backend-watch-api-micro-88@kubernetescrd|watch-backend-watch-api-mono-88@kubernetescrd\"}[1m])*60)",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Open Connections (mono)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=\"watch-backend-watch-api-mono-88@kubernetescrd\"})",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Top 5 all return code (mono)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{service=\"watch-backend-watch-api-mono-88@kubernetescrd\", code!=\"200\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time (mono)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"watch-backend-watch-api-mono-88@kubernetescrd\"}) / sum(traefik_service_requests_total{service=\"watch-backend-watch-api-mono-88@kubernetescrd\"}) * 1000"
    }
   ]
  },
  {
   "title": "Average response time (mono)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"watch-backend-watch-api-mono-88@kubernetescrd\"}) / sum(traefik_service_requests_total{service=\"watch-backend-watch-api-mono-88@kubernetescrd\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Total requests ( mono)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"watch-backend-watch-api-mono-88@kubernetescrd\"}[1m])*60)",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Open Connections (micro)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_service_open_connections{service=\"watch-backend-watch-api-micro-88@kubernetescrd\"})",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Top 5 all return code (micro)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{service=\"watch-backend-watch-api-micro-88@kubernetescrd\", code!=\"200\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Average response time (micro)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"watch-backend-watch-api-micro-88@kubernetescrd\"}) / sum(traefik_service_requests_total{service=\"watch-backend-watch-api-micro-88@kubernetescrd\"}) * 1000"
    }
   ]
  },
  {
   "title": "Average response time (micro)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{service=\"watch-backend-watch-api-micro-88@kubernetescrd\"}) / sum(traefik_service_requests_total{service=\"watch-backend-watch-api-micro-88@kubernetescrd\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Total requests (micro)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"watch-backend-watch-api-micro-88@kubernetescrd\"}[1m])*60)",
     "legendFormat": "Total requests"
    }
   ]
  }
 ]
}