kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "postgres.claimName" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi