apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
type: Opaque
data:
  PostgresUser: {{ .Values.global.pgUser | b64enc | quote }}
  PostgresPassword: {{ .Values.global.pgPass | b64enc | quote }}

