apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
type: Opaque
data:
  PostgresUser: {{ .Values.global.pgUser | b64enc | quote }}
  PostgresPassword: {{ .Values.global.pgPass | b64enc | quote }}
  azSasToken: {{ .Values.global.azSasToken | b64enc | quote }}
  azContainerName: {{ .Values.global.azContainerName | b64enc | quote }}
  azStorageAccount: {{ .Values.global.azStorageAccount | b64enc | quote }}
