apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.global.deployEnv "dev" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      protocol: TCP
      {{- if eq .Values.global.deployEnv "dev" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
