apiVersion: v1
kind: Secret
metadata:
  name: {{ include "btsync.fullname" . }}
type: Opaque
data:
  clientId: {{ .Values.global.kcClientIdBtsync | b64enc | quote }}
  clientSecret: {{ .Values.global.kcClientSecretBtsync | b64enc | quote }}
  cookieSecret: {{ .Values.global.oauthCookieSecret | b64enc | quote  }}