apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "nodeExporter.labels" . | nindent 4 }}
  name: {{ .Values.nodeExporter.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "nodeExporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nodeExporter.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.nodeExporter.name }}
          image: {{ .Values.nodeExporter.repository }}:{{ .Values.nodeExporter.tag }}
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --path.rootfs=/host/root
            - --web.listen-address=:{{ .Values.nodeExporter.hostPort }}
          ports:
            - name: metrics
              containerPort: {{ .Values.nodeExporter.hostPort }}
              hostPort: {{ .Values.nodeExporter.hostPort }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /host/root
              mountPropagation: HostToContainer
              readOnly: true
      hostNetwork: true
      hostPID: true
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule

      securityContext:
        fsGroup: 65534
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534

      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /

