apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "watch-micro.fullname" (list . "") }}-default
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "watch-micro.fullname" (list . .Values.api.nameSuffix) }}
          port: {{ .Values.api.ports.service }}
  tls: {}