apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "watch-micro.fullname" (list . "") }}-watch-api
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: PathPrefix(`/watch-api`)
    kind: Rule
    services:
    - name: {{ include "watch-micro.fullname" (list . .Values.api.nameSuffix) }}
      port: {{ .Values.api.ports.service }}

  tls: {}