apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watch-micro.fullname" (list . "")}}
type: Opaque
data:
  pgUser: {{ .Values.global.pgUser | b64enc | quote }}
  pgPassword: {{ .Values.global.pgPass | b64enc | quote }}
  authToken: {{ .Values.global.authToken | b64enc | quote }}
  wsLocationKey: {{ .Values.global.wsLocationKey | b64enc | quote }}
  wsOpenWeatherKey: {{ .Values.global.wsOpenWeatherKey | b64enc | quote }}
  wsCurrencyConverterKey: {{ .Values.global.wsCurrencyConverterKey | b64enc | quote }}
  wsTwelveDataKey: {{ .Values.global.wsTwelveDataKey | b64enc | quote }}
  wsAppleDarkSkyKey: {{ .Values.global.wsAppleDarkSkyKey | b64enc | quote }}
  telegramBotApiToken: {{ .Values.global.TelegramBotApiToken | b64enc | quote }}
  pgUrl: {{ .Values.global.pgUrl | b64enc | quote }}