apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watch-api-mono.fullname" . }}
  labels:
    {{- include "watch-api-mono.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "watch-api-mono.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watch-api-mono.selectorLabels" . | nindent 8 }}
    spec:
      containers:

        - name: nginx
          image: nginx:alpine
          ports: 
            - containerPort: {{ .Values.ports.nginxContainer }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-log
              mountPath: /var/log/nginx
            - name: nginx-static
              mountPath: /var/www/html
          resources:
            limits:
              memory: "50Mi"

        - name: {{ .Chart.Name }}
          image: ilaverlin/watch-server:latest
          ports:
            - containerPort: {{ .Values.ports.appContainer }}
          env:
            - name: FaceSettings__DisableMsExport
              value: "true"
            - name: FaceSettings__IsPgExportDisabled
              value: "false"
            - name: PostgresProviderSettings__Server
              value: {{ .Values.databaseServer }}
            - name: FaceSettings__LocationKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: WS_LOCATION_KEY
            - name: FaceSettings__DarkSkyKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: WS_DARK_SKY_KEY
            - name: FaceSettings__OpenWeatherKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: WS_OPEN_WEATHER_KEY
            - name: FaceSettings__CurrencyConverterKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: WS_CURRENCY_CONVERTER_KEY
            - name: FaceSettings__AuthSettings__Token
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: WS_AUTH_TOKEN
            - name: FaceSettings__TelegramKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: TELEGRAM_YAS_BOT_KEY
            - name: FaceSettings__DisableYasBot
              value: "true"
            - name: PostgresProviderSettings__UserId
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: PostgresUser
            - name: PostgresProviderSettings__Password
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: PostgresPassword
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: {{ include "watch-api-mono.fullname" . }}
                  key: APP_INSIGHTS_KEY
            {{- if .Values.seqServerUrl }}
            - name: Serilog__WriteTo__1__Args__serverUrl
              value: {{ .Values.seqServerUrl }}
            {{- end}}
            - name: Serilog__WriteTo__2__Args__uri
              value: {{ .Values.lokiServerUrl }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "watch-api-mono.fullname" . }}
        - name: nginx-log
          hostPath:
            path: {{ .Values.global.storageRoot }}/persist/nginx-mono/log
            type: DirectoryOrCreate
        - name: nginx-static
          hostPath:
            path: {{ .Values.global.storageRoot }}/persist/wwwroot
            type: Directory

