apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watch-api-mono.fullname" . }}
type: Opaque
data:
  PostgresUser: {{ .Values.global.pgUser | b64enc | quote }}
  PostgresPassword: {{ .Values.global.pgPass | b64enc | quote }}
  WS_LOCATION_KEY: {{ .Values.global.wsLocationKey | b64enc | quote }}
  WS_DARK_SKY_KEY: {{ .Values.global.wsDarkSkyKey | b64enc | quote }}
  WS_OPEN_WEATHER_KEY: {{ .Values.global.wsOpenWeatherKey | b64enc | quote }}
  WS_CURRENCY_CONVERTER_KEY: {{ .Values.global.wsCurrencyConverterKey | b64enc | quote }}
  WS_AUTH_TOKEN: {{ .Values.global.authToken | b64enc | quote }}
  TELEGRAM_YAS_BOT_KEY: {{ .Values.global.TelegramBotApiToken | b64enc | quote }}
  APP_INSIGHTS_KEY: {{ .Values.global.appInsightsKey | b64enc | quote }}