apiVersion: v1
kind: Service
metadata:
  name: {{ include "watch-api-mono.fullname" . }}
  labels:
    {{- include "watch-api-mono.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.service | quote }}
spec:
  selector:
    {{- include "watch-api-mono.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.ports.service }}
      targetPort: {{ .Values.ports.nginxContainer }}
      protocol: TCP
      name: http

