
nameOverride: ""
fullnameOverride: ""

ports:
  appContainer: 80
  nginxContainer: 8080
  service: 8080

databaseServer: pg-server.database
seqServerUrl: http://seq.monitoring:5341
lokiServerUrl: http://loki.monitoring:3100

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
  #   cpu: 100m
    memory: 200Mi
