apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
type: Opaque
data:
  PG_USER: {{ .Values.global.pgUser | b64enc | quote }}
  PG_PASS: {{ .Values.global.pgPass | b64enc | quote }}