apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sponsor-block.fullname" . }}
  labels:
    {{- include "sponsor-block.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sponsor-block.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sponsor-block.labels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          volumeMounts:
            - name: config-dir
              mountPath: /app/data

      volumes:
        - name: config-dir
          hostPath:
            path: /mnt/data-disk/services/sponsorblock


