apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vpn-server.fullname" . }}
type: Opaque
data:
  VPN_IPSEC_PSK: {{ .Values.global.vpnIpsecPsk | b64enc | quote }}
  VPN_USER: {{ .Values.global.vpnUser | b64enc | quote }}
  VPN_PASSWORD: {{ .Values.global.vpnPassword | b64enc | quote }}
  VPN_EXTRA_USERS: {{ .Values.global.vpnExtraUsers | b64enc | quote }}
  VPN_EXTRA_PASSWORDS: {{ .Values.global.vpnExtraPasswords | b64enc | quote }}