apiVersion: v1
kind: Service
metadata:
  name: {{ include "vpn-server.fullname" . }}
  labels:
    {{- include "vpn-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 500
      targetPort: 500
      nodePort: 30500
      protocol: UDP
      name: udp-500
    - port: 4500
      targetPort: 4500
      nodePort: 30450
      protocol: UDP
      name: udp-4500
  selector:
    {{- include "vpn-server.selectorLabels" . | nindent 4 }}
