apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: stripprefix
  namespace: {{ .Release.Namespace }}
spec:
  stripPrefix:
    prefixes:
      - {{ .Values.console.dashboardPath }}/
---


apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "minio.fullname" . }}-web
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`{{ .Values.global.domainName }}`) && PathPrefix(`{{ .Values.console.dashboardPath }}/`)
    kind: Rule
    middlewares:
    - name: stripprefix
    services: 
    - name: {{ include "minio.fullname" . }}
      port: {{ .Values.console.port }}
  tls: {}

---
# API
#
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "minio.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
  - websecure
  routes:
  - match: Host(`s3.{{ .Values.global.domainName }}`)
    kind: Rule
    services: 
    - name: {{ include "minio.fullname" . }}
      port: {{ .Values.api.port }}
  tls: {}