apiVersion: v1
kind: Secret
metadata:
  name: {{ include "minio.fullname" . }}
type: Opaque
data:
  clientId: {{ .Values.global.kcClientIdMinio | b64enc | quote }}
  clientSecret: {{ .Values.global.kcClientSecretMinio | b64enc | quote }}
