apiVersion: v1
kind: Service
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  type: {{ .Values.console.type }}
  ports:
    - port: {{ .Values.console.port }}
      targetPort: console
      protocol: TCP
      name: console
    - port: {{ .Values.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "minio.selectorLabels" . | nindent 4 }}
