apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  allow-snippet-annotations: "false"
  config.yaml: |
    auth_enabled: false

    server:
      http_listen_port: {{ .Values.ports.containerPort }}
      grpc_listen_port: {{ .Values.ports.grpcContainerPort }}

    common:
      replication_factor: 1
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: inmemory
      path_prefix: /loki

    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        shared_store: s3
      aws:
        s3: http://0sJ7pqfxsZ2h6mLc7Qb7:hRFZ075ghIlwHTMbFANdchfdwgh2BDNNsBNdHV1H@minio.database:9000/loki
        s3forcepathstyle: true

    compactor:
      working_directory: /loki/compactor
      shared_store: s3
      compaction_interval: 5m
      
    ruler:
      alertmanager_url: http://localhost:9093