apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ports.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
