apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.global.deployEnv "dev" }}
  type: NodePort
  {{- end }}
  ports:
    - port: {{ default .Values.ports.containerPort .Values.ports.servicePort }}
      {{- if eq .Values.global.deployEnv "dev" }}
      nodePort: {{ .Values.ports.nodePort }}
      {{- end }}
      targetPort: {{ .Values.ports.containerPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
