## Mount shared drive
##
- name: Mount shared drive on master
  hosts: barolo
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Get data disk if exists
      ansible.builtin.shell: 'lsblk -o label | grep -i "shared-disk" || true'
      register: disk_output
        
    - name: Attach data disk
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "parted /dev/sdc --script mklabel gpt mkpart xfspart xfs 0% 100%"
        - "mkfs.xfs /dev/sdc1"
        - "partprobe /dev/sdc1"
        - "xfs_admin -L shared-disk /dev/sdc1"
      when: disk_output.stdout.find('shared-disk') == -1

    - name: Make shared dir
      ansible.builtin.file:
        path: "{{ secret_vars.storage_root }}"
        state: directory
        
    - name: Setup mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "LABEL=shared-disk   {{ secret_vars.storage_root }}   xfs   defaults,nofail   1   2" 

    - name: mount 
      command: mount -a

    - name: Install NFS server
      ansible.builtin.apt: 
        name:
          - nfs-kernel-server
        state: present

    - name: Config NFS server 
      ansible.builtin.lineinfile:
        path: /etc/exports
        line: "{{ secret_vars.storage_root }} 10.12.0.0/24(rw,sync,no_subtree_check)" 

    - name: get ip
      shell: "hostname -I | awk '{print $1}'"
      register: master_ip

    - name: restart NFS
      shell: "sudo systemctl restart nfs-kernel-server"

    - name: Make persist dir
      ansible.builtin.file:
        path: "{{ secret_vars.storage_root }}/persist/ssl"
        recurse: yes
        state: directory

    - name: Make fake certificate to map in config
      ansible.builtin.copy:
        dest: "{{ secret_vars.storage_root }}/persist/ssl/{{ envs.domain_name }}.full"
        content: |
          -----BEGIN CERTIFICATE-----
          MIIFVDCCBDygAwIBAgIRAO1dW8lt+99NPs1qSY3Rs8cwDQYJKoZIhvcNAQELBQAw
          cTELMAkGA1UEBhMCVVMxMzAxBgNVBAoTKihTVEFHSU5HKSBJbnRlcm5ldCBTZWN1
          cml0eSBSZXNlYXJjaCBHcm91cDEtMCsGA1UEAxMkKFNUQUdJTkcpIERvY3RvcmVk
          IER1cmlhbiBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQw
          M1owZjELMAkGA1UEBhMCVVMxMzAxBgNVBAoTKihTVEFHSU5HKSBJbnRlcm5ldCBT
          ZWN1cml0eSBSZXNlYXJjaCBHcm91cDEiMCAGA1UEAxMZKFNUQUdJTkcpIFByZXRl
          bmQgUGVhciBYMTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALbagEdD
          Ta1QgGBWSYkyMhscZXENOBaVRTMX1hceJENgsL0Ma49D3MilI4KS38mtkmdF6cPW
          nL++fgehT0FbRHZgjOEr8UAN4jH6omjrbTD++VZneTsMVaGamQmDdFl5g1gYaigk
          kmx8OiCO68a4QXg4wSyn6iDipKP8utsE+x1E28SA75HOYqpdrk4HGxuULvlr03wZ
          GTIf/oRt2/c+dYmDoaJhge+GOrLAEQByO7+8+vzOwpNAPEx6LW+crEEZ7eBXih6V
          P19sTGy3yfqK5tPtTdXXCOQMKAp+gCj/VByhmIr+0iNDC540gtvV303WpcbwnkkL
          YC0Ft2cYUyHtkstOfRcRO+K2cZozoSwVPyB8/J9RpcRK3jgnX9lujfwA/pAbP0J2
          UPQFxmWFRQnFjaq6rkqbNEBgLy+kFL1NEsRbvFbKrRi5bYy2lNms2NJPZvdNQbT/
          2dBZKmJqxHkxCuOQFjhJQNeO+Njm1Z1iATS/3rts2yZlqXKsxQUzN6vNbD8KnXRM
          EeOXUYvbV4lqfCf8mS14WEbSiMy87GB5S9ucSV1XUrlTG5UGcMSZOBcEUpisRPEm
          QWUOTWIoDQ5FOia/GI+Ki523r2ruEmbmG37EBSBXdxIdndqrjy+QVAmCebyDx9eV
          EGOIpn26bW5LKerumJxa/CFBaKi4bRvmdJRLAgMBAAGjgfEwge4wDgYDVR0PAQH/
          BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFLXzZfL+sAqSH/s8ffNE
          oKxjJcMUMB8GA1UdIwQYMBaAFAhX2onHolN5DE/d4JCPdLriJ3NEMDgGCCsGAQUF
          BwEBBCwwKjAoBggrBgEFBQcwAoYcaHR0cDovL3N0Zy1kc3QzLmkubGVuY3Iub3Jn
          LzAtBgNVHR8EJjAkMCKgIKAehhxodHRwOi8vc3RnLWRzdDMuYy5sZW5jci5vcmcv
          MCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQBgt8TAQEBMA0GCSqGSIb3DQEB
          CwUAA4IBAQB7tR8B0eIQSS6MhP5kuvGth+dN02DsIhr0yJtk2ehIcPIqSxRRmHGl
          4u2c3QlvEpeRDp2w7eQdRTlI/WnNhY4JOofpMf2zwABgBWtAu0VooQcZZTpQruig
          F/z6xYkBk3UHkjeqxzMN3d1EqGusxJoqgdTouZ5X5QTTIee9nQ3LEhWnRSXDx7Y0
          ttR1BGfcdqHopO4IBqAhbkKRjF5zj7OD8cG35omywUbZtOJnftiI0nFcRaxbXo0v
          oDfLD0S6+AC2R3tKpqjkNX6/91hrRFglUakyMcZU/xleqbv6+Lr3YD8PsBTub6lI
          oZ2lS38fL18Aon458fbc0BPHtenfhKj5
          -----END CERTIFICATE-----
      when: secret_vars.deploy_env != 'prod'

    - name: set permission for shared folder
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "chown -R nobody:nogroup {{ secret_vars.storage_root }}"
        - "chmod -R 777 {{ secret_vars.storage_root }}"

- name: Mount shared drive on workers
  hosts: all,!barolo
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install NFS client
      ansible.builtin.apt: 
        name:
          - nfs-common
        state: present

    - name: Make shared dir
      ansible.builtin.file:
        path: "{{ secret_vars.storage_root }}"
        state: directory

    - name: Setup mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "{{ hostvars['barolo']['master_ip']['stdout'] }}:{{ secret_vars.storage_root }}    {{ secret_vars.storage_root }}    nfs    defaults    0 0" 

    - name: mount 
      command: mount -a
