## Mount shared drive
##
- name: Mount shared drive
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:

    - name: Make shared dir
      ansible.builtin.file:
        path: /shared-data
        state: directory

    - name: Create credentials file
      ansible.builtin.lineinfile:
        path: /etc/smbcredentials
        line: "{{ item }}"
        create: true
      with_items: 
        - "username={{ secret_vars.azure_storage_account }}"
        - "password={{ secret_vars.azure_storage_key }}"
        
    - name: Setup boot mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "//commonblob2store.file.core.windows.net/{{ secret_vars.azure_storage_data }} /shared-data cifs nofail,nobrl,credentials=/etc/smbcredentials,serverino,nosharesock,actimeo=30" 

    - name: mount 
      command: mount -a