## Setup worker node 
##
- name: Setup worker node
  hosts: worker
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:

    - name: Join the Worker nodes with master
      shell: "{{ hostvars['K8S_JOIN_HOLDER']['join_command'] }}"
      register: joined_or_not
      args:
        creates: /etc/kubernetes/kubelet.conf

    - debug:
        msg: "{{ joined_or_not.stdout }}"

    - name: Create directory for kube config.
      ansible.builtin.file: 
        path: /home/{{ ansible_user }}/.kube
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/{{ ansible_user }}/.kube/config
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0644

    - name: Remove the cache directory.
      ansible.builtin.file: 
        path: /home/{{ ansible_user }}/.kube/cache
        state: absent

    - name: Remove master/control roles
      become: false
      ignore_errors: true
      command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane- node-role.kubernetes.io/master-"