- name: Remove taint
  hosts: master, barolo
  become: false

  tasks:
    - name: Remove master/control roles
      ignore_errors: true
      command: kubectl taint nodes --all node-role.kubernetes.io/control-plane- 
      #node-role.kubernetes.io/master-