## Setup worker node 
##
- name: Setup worker node
  hosts: worker
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
       
  tasks:

    - name: Copy join command to worker nodes.
      copy:
        src: /tmp/kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777   

    - name: Join the Worker nodes with master.
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
      args:
        creates: /etc/kubernetes/kubelet.conf

    - debug:
        msg: "{{ joined_or_not.stdout }}"