- name: Create namespaces
  hosts: master
  gather_facts: true
  tasks:

    - name: apply ns
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "kubectl create namespace ingress --dry-run=client -o yaml | kubectl apply -f -"
    #    - "kubectl create namespace kubernetes-dashboard --dry-run=client -o yaml | kubectl apply -f -"
        - "kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -"
        - "kubectl create namespace watch-backend --dry-run=client -o yaml | kubectl apply -f -"
        - "kubectl create namespace side-services --dry-run=client -o yaml | kubectl apply -f -"
 