- name: Generate vars
  hosts: localhost
  tasks:

    - name: generate global vars file for helm
      copy:
        dest: ../../helm/generated-values.yaml
        content: |
          global:
            deployEnv: {{ secret_vars.deploy_env }}
            publicIp: {{ public_ip }}
            storageRoot: {{ secret_vars.storage_root }}
            clusterSecretStoreName: {{ secret_vars.cluster_secret_store_name }}
            tlsStoreName: {{ secret_vars.tls_store_name }}
            domainName: {{ envs.domain_name }}
            oidcIssuerUrl: {{ common.oidc_issuer_url }}
            keycloakHostname: {{ secret_vars.keycloak_subdomain }}{{ envs.domain_name }}
            pgUser: {{ envs.postgres_user }}
            pgPass: {{ envs.postgres_password }}
            oauthCookieSecret: {{ secret_vars.oauth_cookiesecret }}
            kcClientIdK8s: {{ secret_vars.kc_clientid_k8s }}
            kcClientSecretK8s: {{ secret_vars.kc_clientsecret_k8s }}
            kcGroupK8s: {{ secret_vars.kc_group_k8s }}
            kcClientIdGf: {{ secret_vars.kc_clientid_gf }}
            kcClientSecretGf: {{ secret_vars.kc_clientsecret_gf }}
            

            NamecomUser: {{ secret_vars.namecom_user }}
            NamecomToken: {{ secret_vars.namecom_token }}
            TelegramBotApiToken: {{ envs.telegram_bot_api_token }}
            TelegramBotChatId: '{{ secret_vars.telegram_chat_id }}'

