- name: Deploy Azure  Disk
  hosts: master
  gather_facts: true
  tasks:

    - name: Install Azure Disk drivers
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "kubectl create configmap azure-cred-file --from-literal=path=\"/etc/kubernetes/cloud-config/azure.json\" -n kube-system --dry-run -o yaml | kubectl apply -f -"
        - curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/v1.20.0/deploy/install-driver.sh | bash -s v1.20.0 snapshot --

    - name: Install Azure Disk
      ansible.builtin.shell: 
        cmd: |
          cat <<EOF | kubectl apply -f - 
          apiVersion: v1
          kind: PersistentVolume
          metadata:
            name: pv-azuredisk
          spec:
            capacity:
              storage: 30Gi
            accessModes:
              - ReadWriteOnce
            persistentVolumeReclaimPolicy: Retain
            storageClassName: managed-csi
            csi:
              driver: disk.csi.azure.com
              readOnly: false
              volumeHandle: {{ secret_vars.azure_disk }}
              volumeAttributes:
                fsType: ext4  
          EOF
        