- name: Deploy Traefik
  hosts: master
  gather_facts: true
  tasks:
 
    - name: Copy traefik setup files
      ansible.builtin.copy:
        src: ./../../kubernetes/traefik
        dest: ~/kubernetes
        force: yes 
        
    - name: Variable substitution
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - 'sed "s|#%ACME_SERVER%#|{{ secret_vars.acme_server }}|g" ~/kubernetes/traefik/04-deployment-template.yaml > ~/kubernetes/traefik/04-deployment.yaml'

    - name: Create namespace & secrets
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - "kubectl create namespace ingress --dry-run=client -o yaml | kubectl apply -f -"
        - "[ -f .env ] && kubectl create secret generic secret-data --from-env-file .env --namespace=ingress --dry-run=client -o yaml | kubectl apply -f -"
      register: out
      failed_when: out.stderr != ''

    - name: Deploy acme.sh certificate manager
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - kubectl apply -f $HOME/kubernetes/traefik/00-setup-ssl.yaml
        - kubectl wait deployment -n ingress acme-sh --for condition=Available=True --timeout=90s
        - kubectl exec deploy/acme-sh -n ingress -- --set-notify --notify-hook telegram
        - kubectl exec deploy/acme-sh -n ingress -- --issue -d {{ secret_vars.namecom_fqn }} --dns dns_namecom --server letsencrypt.org --key-file /acmeout/{{ secret_vars.namecom_fqn }}.key --fullchain-file /acmeout/{{ secret_vars.namecom_fqn }}.full 
      args:
        creates: /shared-data/persist/ssl/{{ secret_vars.namecom_fqn }}.full


    - name: Deploy Traefik 
      ansible.builtin.shell: "{{ item }}"
      with_items:       
        - kubectl apply -f $HOME/kubernetes/traefik/01-definitions.yaml
        - kubectl apply -f $HOME/kubernetes/traefik/03-rbac.yaml
        - kubectl apply -f $HOME/kubernetes/traefik/04-deployment.yaml
        - kubectl apply -f $HOME/kubernetes/traefik/05-service.yaml
        - kubectl apply -f $HOME/kubernetes/traefik/06-dashboards.yaml

    # - name: Deploy test
    #   ansible.builtin.command: "{{ item }}"
    #   with_items: 
    #     - kubectl apply -f $HOME/kubernetes/test/whoami-m.yaml
    #     - kubectl apply -f $HOME/kubernetes/test/whoami-w.yaml