- name: Generate vars
  hosts: localhost
  tasks:

    - name: generate global vars file for helm
      copy:
        dest: ../../helm/secret.{{ secret_vars.deploy_env }}-values.yaml
        content: |
          global:
            deployEnv: {{ secret_vars.deploy_env }}
            podSubnet: {{ secret_vars.pod_subnet }}
            publicIp: {{ public_ip }}
            storageRoot: {{ envs.storage_root }}
            clusterSecretStoreName: {{ secret_vars.cluster_secret_store_name }}
            tlsStoreName: {{ secret_vars.tls_store_name }}
            domainName: {{ envs.domain_name }}
            prod_iSplitDomain: {{ secret_vars.prod_isplit_fqn }} 
            isplitDomain: {{ envs.isplit_domain }}
            isplitApiDomain: {{ envs.isplit_api_domain }}
            oidcIssuerUrl: {{ common.oidc_issuer_url }}
            keycloakHostname: {{ secret_vars.keycloak_subdomain }}{{ envs.domain_name }}
            azStorageAccount: {{ secret_vars.azure_storage_account }}
            azSasToken: '{{ secret_vars.azure_sas_token }}'
            azContainerName: {{ secret_vars.azure_container_name }}
            pgUser: {{ envs.postgres_user }}
            pgPass: {{ envs.postgres_password }}
            pgUrl: 'user={{ envs.postgres_user }} password={{ envs.postgres_password }} host=pg-server.database port=5432 dbname=WatchService'
            isaPgUrl: 'Server=pg-server.database;Port=5432;Database=isplitapp;User Id={{ envs.postgres_user }};Password={{ envs.postgres_password }};'
            plexPort: {{ secret_vars.plex_port }}
            qbtPort: {{ secret_vars.qbt_port }}


            vapidSubject: '{{ secret_vars.vapid_subject }}'
            vapidPublicKey: '{{ secret_vars.vapid_public_key }}'
            vapidPrivateKey: '{{ secret_vars.vapid_private_key }}'

            oauthCookieSecret: {{ secret_vars.oauth_cookiesecret }}
            kcClientIdK8s: {{ secret_vars.kc_clientid_k8s }}
            kcClientSecretK8s: {{ envs.kc_clientsecret_k8s }}
            kcGroupK8s: {{ secret_vars.kc_group_k8s }}
            kcClientIdGf: {{ secret_vars.kc_clientid_gf }}
            kcClientSecretGf: {{ envs.kc_clientsecret_gf }}
            kcClientIdWireguard: {{ secret_vars.kc_clientid_wireguard }}
            kcClientSecretWireguard: {{ envs.kc_clientsecret_wireguard }}
            kcGroupWireguard: {{ secret_vars.kc_group_wireguard }}
            kcGroupBtsync: {{ secret_vars.kc_group_btsync }}
            kcClientIdBtsync: {{ secret_vars.kc_clientid_btsync }}
            kcClientSecretBtsync: {{ envs.kc_clientsecret_btsync }}
            kcClientIdMinio: {{ secret_vars.kc_clientid_minio }}
            kcClientSecretMinio: {{ envs.kc_clientsecret_minio }}
            
            NamecomDomain: {{ secret_vars.namecom_domain }}
            NamecomUser: {{ secret_vars.namecom_user }}
            NamecomToken: {{ secret_vars.namecom_token }}
            TelegramBotApiToken: {{ envs.telegram_bot_api_token }}
            TelegramBotChatId: '{{ secret_vars.telegram_chat_id }}'

            authToken: '{{ secret_vars.ws_auth_token }}'
            wsLocationKey: '{{ secret_vars.ws_location_key }}'
            wsDarkSkyKey: '{{ secret_vars.ws_dark_sky_key }}'
            wsOpenWeatherKey: '{{ secret_vars.ws_open_weather_key }}'
            wsCurrencyConverterKey: '{{ secret_vars.ws_currency_converter_key }}'
            wsTwelveDataKey: '{{ secret_vars.ws_twelve_data_key }}'
            appInsightsKey: '{{ secret_vars.app_insights_key }}'
            wsAppleDarkSkyKey: '{{ secret_vars.ws_apple_darksky_key }}'

            vpnIpsecPsk: '{{ secret_vars.vpn_pre_shared_key }}'
            vpnUser: '{{ secret_vars.vpn_username }}'
            vpnPassword: '{{ secret_vars.vpn_password }}'
            vpnExtraUsers: '{{ secret_vars.vpn_extra_users }}'
            vpnExtraPasswords: '{{ secret_vars.vpn_extra_passwords }}'

