- name: Copy config files
  hosts: barolo, master
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:

    # - name: Copy config files
    #   ansible.builtin.copy:
    #     src: ./../../configs
    #     dest: /shared-data
    #     force: yes # We always want to have a fresh configs

    - name: Copy wwwroot
      ansible.builtin.copy:
        src: ./../../persist/wwwroot
        dest: "{{ secret_vars.storage_root }}/persist"
        force: yes # And we always want to have a fresh wwwwroot
      when: secret_vars.deploy_env == 'prod' or secret_vars.deploy_env == 'stage'

    - name: Copy wwwroot
      ansible.builtin.copy:
        src: ./../../persist/wwwroot
        dest: "{{ secret_vars.dev_storage_root }}/persist"
        force: yes # And we always want to have a fresh wwwwroot
      when: secret_vars.deploy_env == 'dev'

    # - name: Copy grafana dashboards
    #   ansible.builtin.copy:
    #     src: ./../../persist/grafana
    #     dest: /shared-data/persist
    #     force: no # But the grafana dashboards we want to copy only once (!)

        