- name: Deploy Side Services
  hosts: master
  gather_facts: true
  tasks:

    - name: Copy side services setup files
      ansible.builtin.copy:
        src: ./../../kubernetes/side-services
        dest: ~/kubernetes
        force: yes 

    - name: Deploy services namespace & secrets
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - "kubectl create namespace side-services --dry-run=client -o yaml | kubectl apply -f -"
        - "[ -f .env ] && kubectl create secret generic secret-data --from-env-file .env --namespace=side-services --dry-run=client -o yaml | kubectl apply -f -"
      register: out
      failed_when: out.stderr != ''      

    - name: Deploy side services 
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - kubectl apply -f ~/kubernetes/side-services/vpn.yaml