- name: Deploy Monitoring Tools
  hosts: master
  gather_facts: true
  tasks:

    - name: Copy monitoring setup files
      ansible.builtin.copy:
        src: ./../../kubernetes/monitoring
        dest: ~/kubernetes
        force: yes 
        
    - name: Deploy monitoring secrets
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - "[ -f .env ] && kubectl create secret generic secret-data --from-env-file .env --namespace=monitoring --dry-run=client -o yaml | kubectl apply -f -"
      register: out
      failed_when: out.stderr != ''

    - name: create config map 
      ansible.builtin.shell: |
        kubectl create configmap variables --namespace=monitoring \
          --from-literal=domain_name={{ secret_vars.namecom_fqn }} \
          --from-literal=kd_keycloak_client_secret={{ secret_vars.kd_keycloak_client_secret }} \
          --from-literal=gf_keycloak_client_secret={{ secret_vars.gf_keycloak_client_secret }} \
          --dry-run=client -o yaml | kubectl apply -f - 

    - name: Deploy monitoring
      ansible.builtin.shell: "{{ item }}"
      with_items:    
        - kubectl apply -f ~/kubernetes/monitoring/keycloak.yaml
        - kubectl apply -f ~/kubernetes/monitoring/tempo.yaml
        - kubectl apply -f ~/kubernetes/monitoring/loki.yaml

        - kubectl apply -f ~/kubernetes/monitoring/metrics-server.yaml
        - kubectl apply -f ~/kubernetes/monitoring/kube-state-metrics.yaml   
        - kubectl apply -f ~/kubernetes/monitoring/node-exporter.yaml
        
        - kubectl apply -f ~/kubernetes/monitoring/otel-collector.yaml
        - kubectl apply -f ~/kubernetes/monitoring/prometheus.yaml

        - kubectl apply -f ~/kubernetes/monitoring/grafana.yaml
#        - kubectl apply -f ~/kubernetes/monitoring/kafka-ui.yaml
        - kubectl apply -f ~/kubernetes/monitoring/kubernetes-dashboard.yaml
      #  - kubectl apply -f ~/kubernetes/monitoring/kubernetes-dashboard-account.yaml

