- name: Deploy Watch Backend
  hosts: master
  gather_facts: true
  tasks:

    - name: Copy watch-backend setup files
      ansible.builtin.copy:
        src: ./../../kubernetes/watch-backend
        dest: ~/kubernetes
        force: yes 

    - name: Deploy watch backend namespace & secrets
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - "[ -f .env ] && kubectl create secret generic secret-data --from-env-file .env --namespace=watch-backend --dry-run=client -o yaml | kubectl apply -f -"
      register: out
      failed_when: out.stderr != ''      

    - name: Deploy watch backend containers
      ansible.builtin.shell: "{{ item }}"
      with_items: 
        - kubectl apply -f ~/kubernetes/watch-backend/kafka.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/postgres.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/restore-backup.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/watch-api-mono.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/watch-api-micro.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/traefik-routing.yaml
        - kubectl apply -f ~/kubernetes/watch-backend/pg-backup.yaml


    # - name: Copy test files
    #   ansible.builtin.copy:
    #     src: ./../../kubernetes/test
    #     dest: ~/kubernetes
    #     force: yes 

    # - name: Deploy test
    #   ansible.builtin.command: "{{ item }}"
    #   with_items: 
    #     - kubectl apply -f $HOME/kubernetes/test/whoami-m.yaml
    #     - kubectl apply -f $HOME/kubernetes/test/whoami-w.yaml