- name: Deploy Traefik
  hosts: master
  gather_facts: true
  tasks:

    - name: setup secrets
      ansible.builtin.shell: "{{ item }}"
      with_items:
        - kubectl apply -f $HOME/kubernetes/Traefik/02-namespace.yaml  
        - "kubectl create secret generic secret-data --from-env-file .env --namespace=ingress --dry-run=client -o yaml | kubectl apply -f -"

    - name: Deploy Traefik
      ansible.builtin.command: "{{ item }}"
      with_items: 
          - kubectl apply -f $HOME/kubernetes/Traefik/01-definitions.yaml
          - kubectl apply -f $HOME/kubernetes/Traefik/03-rbac.yaml
          - kubectl apply -f $HOME/kubernetes/Traefik/04-deployment.yaml
          - kubectl apply -f $HOME/kubernetes/Traefik/05-service.yaml
          - kubectl apply -f $HOME/kubernetes/Traefik/06-dashboards.yaml