## Mount shared drive
##
- name: mount shared drive
  hosts: all
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  tasks:
    - name: make dir
      ansible.builtin.file:
        path: /shared-data
        state: directory

    - name: setup boot mount
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: LABEL=data-disk /shared-data ext4 defaults,nofail 0 0

    - name: mount 
      command: mount -a