apiVersion: 1

datasources:
  - name: Prometheus
    uid: "PBFA97CFB590B2093"
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: PostgreSQL
    type: postgres
    url: pg-server.watch-backend:5432
    database: WatchService
    user: $PG_USER
    editable: true
    secureJsonData:
      password: $PG_PASS
    jsonData:
      sslmode: "disable"

  - id: 7
    uid: lik25zR4k
    orgId: 1
    name: Loki
    type: loki
    typeName: Loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
      - datasourceUid: soa9NzgVz
        matcherRegex: '"TraceId":"(\w+)"'
        name: TraceID
        url: "${__value.raw}"
      manageAlerts: false
    readOnly: false

  - id: 6
    uid: soa9NzgVz
    orgId: 1
    name: Tempo
    type: tempo
    typeName: Tempo
    access: proxy
    url: http://tempo:3200
    user: ''
    database: ''
    basicAuth: false
    isDefault: false
    jsonData:
      lokiSearch:
        datasourceUid: lik25zR4k
      nodeGraph:
        enabled: true
      tracesToLogs:
        datasourceUid: lik25zR4k
        filterBySpanID: true
        filterByTraceID: true
        mapTagNamesEnabled: true
        mappedTags:
        - key: job
          value: ''
        - key: instance
          value: ''
    readOnly: false
