apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "acme-sh.fullname" . }}
  labels:
    {{- include "acme-sh.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources: 
  - secrets
  - pods
  - pods/exec
  verbs: 
  - "*"
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch