apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acme-sh.fullname" . }}
type: Opaque
data:
  NamecomUser: {{ .Values.global.NamecomUser | b64enc | quote }}
  NamecomToken: {{ .Values.global.NamecomToken | b64enc | quote }}
  TelegramBotApiToken: {{ .Values.global.TelegramBotApiToken | b64enc | quote }}
  TelegramBotChatId: {{ .Values.global.TelegramBotChatId | b64enc | quote }}