# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: postgres
  tag: "alpine"

nameOverride: ""
fullnameOverride: "pg-server"

pgSecret: "postgres"

resources: 
  requests:
    cpu: ".2"
    memory: "100Mi"

nodeSelector: 
  node-role: master

tolerations: 
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"

affinity: {}

service:
  type: ClusterIP
  port: 5432
