# Default values for postgres.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: postgres
  tag: "15-alpine"

nameOverride: ""
fullnameOverride: "pg-server"

pgSecret: "postgres"

resources: {}
  # limits:
  #   memory: 500Mi
  #   hugepages-2Mi: 200Mi
#   requests:
#     cpu: ".2"
#     memory: "100Mi"

nodeSelector: 
  node-role: master

tolerations: 
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

affinity: {}

service:
  port: 5432
  nodePort: 30543

backupDatabase: "WatchService"
backupDatabaseKC: "keycloak"
backupContainerKC: "pg-backup-kc"
backupDatabaseGF: "grafana"
backupContainerGF: "pg-backup-gf"
