kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka
  namespace: watch-backend
spec:
  selector:
    matchLabels:
        app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: debezium/kafka
          ports:
            - containerPort: 9092
              name: kafka-port
            - containerPort: 9093
              name: controller-port
          env:
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx380M -Xms256M"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: CLUSTER_ID
              value: "5Yr1SIgYQz-b-dgRabWx4g"
            - name: NODE_ID
              value: "1"
            - name: CONTROLLER_QUORUM_VOTERS
              value: 1@kafka:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: LOG_DIR
              value: /kafka/data/logs
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka.watch-backend:9092

          securityContext:
            runAsUser: 0
            privileged: true
          resources:
              requests:
                memory: "400Mi"
          volumeMounts:
            - name: kafka-data
              mountPath: /kafka/data

        - name: kafka-exporter
          image: bitnami/kafka-exporter:latest
          ports: 
            - containerPort: 9308
          args: 
            - --kafka.server=localhost:9092
          resources:
            requests:
              memory: "50Mi"

      volumes:
        - name: kafka-data
          hostPath:
            path: /shared-data/persist/kafka
            type: DirectoryOrCreate

---
# service
#
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: watch-backend
spec:
  selector:
    app: kafka
  ports:
    - port: 9092
      name: kafka-port
    - port: 9093
      name: controller-port
    - port: 9308
      name: exporter-port
    - port: 5556
      name: jmx-port
