apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-api-mono
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-api-mono
  template:
    metadata:
      labels:
        app: watch-api-mono
    spec:
      volumes:
        - name: nginx-config
          hostPath:
            path: /shared-data/configs/nginx-mono
            type: Directory
        - name: nginx-log
          hostPath:
            path: /shared-data/persist/nginx-mono/log
            type: DirectoryOrCreate
        - name: nginx-static
          hostPath:
            path: /shared-data/persist/wwwroot
            type: Directory
      containers:

        - name: nginx
          image: nginx:alpine
          ports: 
            - containerPort: 88
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-log
              mountPath: /var/log/nginx
            - name: nginx-static
              mountPath: /var/www/html
          resources:
            limits:
              memory: "50Mi"

        - name: watch-server
          image: ilaverlin/watch-server:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
          env:
            # - name: MsSqlProviderSettings__Server
            #   value: mssql-watchbackend.database.windows.net
            # - name: MsSqlProviderSettings__UserId
            #   valueFrom:
            #     secretKeyRef:
            #       name: secret-data
            #       key: MSSQL_USER
            # - name: MsSqlProviderSettings__Password
            #   valueFrom: 
            #     secretKeyRef:
            #       name: secret-data
            #       key: MSSQL_PASSWORD
            - name: FaceSettings__DisableMsExport
              value: "true"

            - name: FaceSettings__IsPgExportDisabled
              value: "false"

            - name: PostgresProviderSettings__Server
              value: pg-server
            - name: FaceSettings__LocationKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_LOCATION_KEY
            - name: FaceSettings__DarkSkyKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_DARK_SKY_KEY
            - name: FaceSettings__OpenWeatherKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_OPEN_WEATHER_KEY
            - name: FaceSettings__CurrencyConverterKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_CURRENCY_CONVERTER_KEY
            - name: FaceSettings__AuthSettings__Token
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_AUTH_TOKEN
            - name: FaceSettings__TelegramKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: TELEGRAM_YAS_BOT_KEY
            - name: FaceSettings__DisableYasBot
              value: "false"
            - name: PostgresProviderSettings__UserId
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_USER
            - name: PostgresProviderSettings__Password
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_PASS
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: APP_INSIGHTS_KEY
            - name: Serilog__WriteTo__1__Args__serverUrl
              value: http://seq.monitoring:5341
            - name: Serilog__WriteTo__2__Args__uri
              value: http://loki.monitoring:3100
          resources:
            requests:
              memory: "200Mi"
---

# Service
#
apiVersion: v1
kind: Service
metadata:
  name: watch-api-mono
  namespace: watch-backend
spec:
  selector:
    app: watch-api-mono
  ports:
    - port: 88
      targetPort: 88

