apiVersion: apps/v1
kind: Deployment
metadata:
  name: watch-api-micro
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: watch-api-micro
  template:
    metadata:
      labels:
        app: watch-api-micro
    spec:
      volumes:
        - name: nginx-config
          hostPath:
            path: /shared-data/configs/nginx-micro
            type: Directory
        - name: nginx-log
          hostPath:
            path: /shared-data/persist/nginx-micro/log
            type: DirectoryOrCreate
        - name: nginx-static
          hostPath:
            path: /shared-data/persist/wwwroot
            type: Directory
      containers:

        - name: nginx
          image: nginx:alpine
          ports: 
            - containerPort: 88
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: nginx-log
              mountPath: /var/log/nginx
            - name: nginx-static
              mountPath: /var/www/html
          resources:
            requests:
              memory: "50Mi"

        - name: watch-api
          image: ilaverlin/watchcluster-api:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 80
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: ApiConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: ApiConfiguration__AuthSettings__Token
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_AUTH_TOKEN
            - name: KafkaConfiguration__BootstrapServers
              value: kafka:9092
            - name: PgProviderConfiguration__server
              value: pg-server.watch-backend
            - name: PgProviderConfiguration__Port
              value: "5432"
            - name: PgProviderConfiguration__UserId
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_USER
            - name: PgProviderConfiguration__Password
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_PASS
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              memory: "100Mi"
---

# Service
#
apiVersion: v1
kind: Service
metadata:
  name: watch-api-micro
  namespace: watch-backend
spec:
  selector:
    app: watch-api-micro
  ports:
    - port: 88


---
# location handler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: ilaverlin/watchcluster-servicehost:latest
          imagePullPolicy: 'Always'
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: AppConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: KafkaConfiguration__BootstrapServers
              value: kafka:9092              
            - name: AppConfiguration__handler 
              value: LocationInfo
            - name: VirtualEarthConfiguration__AuthKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_LOCATION_KEY
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "100Mi"

---
# weather handler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-service
  template:
    metadata:
      labels:
        app: weather-service
    spec:
      containers:
        - name: weather-service
          image: ilaverlin/watchcluster-servicehost:latest
          imagePullPolicy: 'Always'
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: AppConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: KafkaConfiguration__BootstrapServers
              value: kafka:9092              
            - name: AppConfiguration__handler 
              value: WeatherInfo
            - name: WeatherConfiguration__OpenWeatherKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_OPEN_WEATHER_KEY
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "100Mi" 

---
# exchange handler
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-service
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - name: exchange-service
          image: ilaverlin/watchcluster-servicehost:latest
          imagePullPolicy: 'Always'
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: AppConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: KafkaConfiguration__BootstrapServers
              value: kafka:9092              
            - name: AppConfiguration__handler 
              value: ExchangeRateInfo
            - name: CurrencyExchangeConfiguration__CurrencyConverterKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_CURRENCY_CONVERTER_KEY
            - name: CurrencyExchangeConfiguration__TwelveDataKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: WS_TWELVE_DATA_KEY
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "100Mi"

---
# YAS Bot
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sink
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sink
  template:
    metadata:
      labels:
        app: db-sink
    spec:
      containers:
        - name: db-sink
          image: ilaverlin/watchcluster-dbsink:latest
          imagePullPolicy: 'Always'
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: DbSinkConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: KafkaConfiguration__BootstrapServers
              value: kafka:9092             
            - name: PgProviderConfiguration__server
              value: pg-server.watch-backend
            - name: PgProviderConfiguration__UserId
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_USER
            - name: PgProviderConfiguration__Password
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: PG_PASS
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
           requests:
              memory: "50Mi"

---
# Database sink
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yas-bot
  namespace: watch-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yas-bot
  template:
    metadata:
      labels:
        app: yas-bot
    spec:
      containers:
        - name: yas-bot
          image: ilaverlin/watchcluster-yasbot:latest
          imagePullPolicy: 'Always'
          env:
            - name: Serilog__WriteTo__0__Args__uri
              value: http://loki.monitoring:3100
            - name: BotConfiguration__OpenTelemetryCollectorUrl
              value: http://otel-collector.monitoring:4317
            - name: BotConfiguration__BaseStorageApiUrl
              value: http://watch-api-micro:88/api/v2.0/YASail/
            - name: BotConfiguration__BotApiKey
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: TELEGRAM_YAS_BOT_KEY
          startupProbe:
            httpGet:
              path: /health/ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /health/live
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
           requests:
              memory: "50Mi"