apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
  name: {{ .Values.prometheus.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prometheus.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "prometheus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}