apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.serviceAccountName" . }}
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ default .Values.prometheus.containerPort .Values.prometheus.servicePort }}
    containerPort: {{ .Values.prometheus.containerPort }}
    {{ if .Values.prometheus.nodePort -}}
    nodePort: {{ default .Values.prometheus.nodePort }}
    {{ end -}}
    protocol: TCP
  {{ if .Values.prometheus.nodePort -}}
  type: NodePort
  {{- else -}}
  type: ClusterIP
  {{- end }}