apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "kubeStateMetrics.labels" . | nindent 4 }}
  name: {{ .Values.kubeStateMetrics.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kubeStateMetrics.name }}
subjects:
- kind: ServiceAccount
  name: {{ template "kubeStateMetrics.serviceAccountName" . }}
  namespace: {{ .Values.kubeStateMetrics.namespace }}