apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kubeStateMetrics.name }}
  namespace: {{ .Values.kubeStateMetrics.namespace }}
  labels:
    {{- include "kubeStateMetrics.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
  - name: "http"
    protocol: TCP
    port: {{ .Values.kubeStateMetrics.servicePort }}
    targetPort: {{ .Values.kubeStateMetrics.servicePort }}
  - name: "telemetry"
    protocol: TCP
    port: {{ .Values.kubeStateMetrics.telemetryServicePort }}
    targetPort: {{ .Values.kubeStateMetrics.telemetryServicePort }}

  selector:
    {{- include "kubeStateMetrics.selectorLabels" . | nindent 4 }}