apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    {{- include "kubeStateMetrics.labels" . | nindent 4 }}
  name: {{ include "kubeStateMetrics.serviceAccountName" . }}
  namespace: {{ .Values.kubeStateMetrics.namespace }}