
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: ip-filter
spec:
  ipWhiteList:
    sourceRange:
      - 192.168.111.0/24
    ipStrategy:
      depth: 0
---

## Route Rule
##
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "qbt.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: host(`qbt.ivan-b.com`)
      kind: Rule
      middlewares:
        - name: ip-filter
      services:
        - name: {{ include "qbt.fullname" . }}
          port: {{ .Values.service.webPort }}
  tls: {}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: '{{ include "qbt.fullname" . }}-udpptp'
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - udpptp
  routes:
    - services:
      - name: {{ include "qbt.fullname" . }}
        port: {{ .Values.global.qbtPort }}

---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: '{{ include "qbt.fullname" . }}-tcpptp'
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - tcpptp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "qbt.fullname" . }}
          port: {{ .Values.global.qbtPort }}

