apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.grafana.name }}
type: Opaque
data:
  PostgresUser: {{ .Values.global.pgUser | b64enc | quote }}
  PostgresPassword: {{ .Values.global.pgPass | b64enc | quote }}
  kcClientSecret: {{ .Values.global.kcClientSecretGf | b64enc | quote }}

