apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
  name: {{ .Values.grafana.name }}
  namespace: {{ .Release.Namespace }}
spec:

  ports:
    - name: metrics
      port: {{ default .Values.grafana.containerPort .Values.grafana.servicePort }}
      protocol: TCP
      targetPort: {{ .Values.grafana.containerPort }}
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  type: ClusterIP