# Default values for qbt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: hotio/qbittorrent #lscr.io/linuxserver/qbittorrent #qbittorrentofficial/qbittorrent-nox
  tag: "release-4.5.2"

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # runAsUser: 1000
  # runAsGroup: 1000
  # fsGroup: 1000

securityContext: {}
  # capabilities:
  #   add: ["SETGID", "SETPID"]
  # #   drop:
  # #   - ALL
  # # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # runAsGroup: 1000


service:
  type: ClusterIP
  webPort: 8080
  ptpPortContainer: 6881


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


