
- import_playbook: playbooks/mount-drive.yaml
- import_playbook: playbooks/preset-kuber.yaml
- import_playbook: playbooks/setup-master.yaml
- import_playbook: playbooks/setup-worker.yaml

- import_playbook: playbooks/deploy-traefik.yaml





    ## Reboot to make sure everything is fine
    ##
    # - name: Reboot all the kubernetes nodes.
    #   ansible.builtin.reboot:
    #     post_reboot_delay: 10
    #     reboot_timeout: 40
    #     connect_timeout: 60
    #     test_command: uptime
    # - pause: seconds=20


 

