{
 "title": "App Activity",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Traefik", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime Traefik",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - sum(process_start_time_seconds{ pod!=\"\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non Success Responses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{code!=\"200\"}) by (code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "App Requests/Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{ service=\"watch-backend-watch-micro-watch-api-cff2ef34417ffb380310@kubernetescrd\"}[1m])*60) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg App Request Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_router_request_duration_seconds_sum{router=\"watch-backend-watch-micro-watch-api-cff2ef34417ffb380310@kubernetescrd\"}) / sum(traefik_router_request_duration_seconds_count{router=\"watch-backend-watch-micro-watch-api-cff2ef34417ffb380310@kubernetescrd\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "API Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_api_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Requested",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 2, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_locationinfo_processed_counter{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Location"
    },
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Exchange"
    },
    {
     "expr": "sum(delta(wc_weatherinfo_processed_counter{source_kind!=\"Empty\"}[$__range]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Cached",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wc_api_memoryitems_gauge", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "App Requests/Min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(wc_api_httprequest_count[1m])*60)",
     "legendFormat": "req/min"
    }
   ]
  },
  {
   "title": "Avg Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(wc_api_message_duration_sum[1m]))/sum(rate(wc_api_message_duration_count[1m]))",
     "legendFormat": "duration"
    }
   ]
  },
  { "title": "Location Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Location Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_locationinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wc_locationinfo_processed_counter{status=\"Error\"} - wc_locationinfo_processed_counter{status=\"Error\"} offset $__range) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_locationinfo_processed_counter[$__range])) by (source_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cached Items",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "wc_locationinfo_memoryitems_gauge",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Weather Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Weather Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_weatherinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wc_weatherinfo_processed_counter{status=\"Error\"} - wc_weatherinfo_processed_counter{status=\"Error\"} offset $__range) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Weather Providers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_weatherinfo_processed_counter[$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Exchange Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Exchange Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_exchangerateinfo_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wc_exchangerateinfo_processed_counter{status=\"Error\"} - wc_exchangerateinfo_processed_counter{status=\"Error\"} offset $__range) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exchange Rate Providers",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter{source_kind=\"Remote\"}[$__range])) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remote Request/Day ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(wc_exchangerateinfo_processed_counter{source_kind=\"Remote\"} - wc_exchangerateinfo_processed_counter{source_kind=\"Remote\"} offset 24h) by (remote_source)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_exchangerateinfo_processed_counter[$__range])) by (source_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database Sync & YA Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "YA Bot Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - wc_yasbot_uptime_gauge/1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "YA Requests/Day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 3, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(wc_yasbot_message_counter[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Data Anlytics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Uniq visitors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "rawSql": "SELECT * FROM uniq_month;\n" }
   ]
  },
  {
   "title": "Devices :: window",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() as time,\n  COALESCE(D.\"DeviceName\", 'nil') as \"DeviceName\",\n  count(distinct(D.\"DeviceId\")) as \"Count\"\nFROM\n  \"DeviceInfo\" D JOIN \"CityInfo\" C ON D.\"id\" = C.\"DeviceInfoId\" AND $__timeFilter(C.\"RequestTime\")\n\nGROUP BY \n  D.\"DeviceName\"\nORDER BY \"Count\" desc\n"
    }
   ]
  },
  {
   "title": "Devices Total",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT NOW() as time, \"DeviceName\", sum(\"count\") as \"count\" FROM (\r\n    SELECT \"DeviceName\", \"count\" FROM total_devices\r\n    UNION\r\n    SELECT \r\n        COALESCE(\"DeviceName\", 'nil') as \"DeviceName\",\r\n        count(distinct(D.\"DeviceId\")) as \"count\"\r\n    FROM\r\n        \"DeviceInfo\" D JOIN \"CityInfo\" C ON D.\"id\" = C.\"DeviceInfoId\"\r\n    WHERE D.\"FirstRequestTime\" > (SELECT refresh_time FROM view_state WHERE view_name = 'total_devices')\r\n    GROUP BY \r\n        \"DeviceName\"\r\n) td\r\nGROUP BY \"DeviceName\"\r\nORDER BY \"count\" desc;"
    }
   ]
  },
  {
   "title": "Version :: window",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 62 },
   "targets": [
    {
     "rawSql": "select\n  COALESCE(\"FaceVersion\", 'nil') as \"Version\",\n  count(distinct(\"DeviceInfoId\")) as \"Count\"\nfrom \"CityInfo\" \n\nWHERE\n  $__timeFilter(\"RequestTime\")\ngroup by \"FaceVersion\"\norder by \"Count\" desc\n\n"
    }
   ]
  },
  {
   "title": "Version Total",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 62 },
   "targets": [
    {
     "rawSql": "SELECT \"Version\", sum(\"Count\") as \"Count\" FROM (\n    SELECT \"Version\", \"Count\" FROM total_versions\n    UNION\n    select\n        \"FaceVersion\" as \"Version\",\n        count(distinct(\"DeviceInfoId\")) as \"Count\"\n    from \"CityInfo\" C\n    WHERE C.\"RequestTime\" > (SELECT refresh_time FROM view_state WHERE view_name = 'total_versions')\n    group by \"FaceVersion\"\n) tv\nGROUP BY \"Version\"\nORDER BY \"Count\" desc;\n"
    }
   ]
  },
  {
   "title": "Geo visual",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 15, "w": 19, "x": 0, "y": 70 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct(\"DeviceInfoId\")) AS metric,\n  max(\"Lat\") AS lat, max(\"Lon\") lon, \"CityName\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"CityName\" is not NULL\nGROUP BY \"CityName\"\n"
    }
   ]
  },
  {
   "title": "Cities",
   "type": "table-old",
   "gridPos": { "h": 15, "w": 5, "x": 19, "y": 70 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"CityName\",\n  count(distinct(\"DeviceInfoId\")) AS \"Count\"\n\nFROM \"CityInfo\"\nWHERE\n  $__timeFilter(\"RequestTime\") AND \"Lat\" IS NOT NULL\nGROUP BY \"CityName\"\nORDER BY \"Count\""
    }
   ]
  }
 ]
}