# Default values for loki.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: grafana/loki
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

ports:
  containerPort: 3100
  grpcContainerPort: 9096
  servicePort: 3100

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0

resources: 
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 0.1
    memory: 200Mi

