apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wireguard.fullname" . }}
type: Opaque
data:
  clientId: {{ .Values.global.kcClientIdWireguard | b64enc | quote }}
  clientSecret: {{ .Values.global.kcClientSecretWireguard | b64enc | quote }}
  cookieSecret: {{ .Values.global.oauthCookieSecret | b64enc | quote  }}
