apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard.fullname" . }}
  labels:
    {{- include "wireguard.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.ports.vpnPort }}
      port: {{ .Values.ports.vpnPort }}
      targetPort: vpn-port
      protocol: UDP
      name: vpn
    - port: {{ .Values.ports.oauth }}
      protocol: TCP
      name: oauth
  selector:
    {{- include "wireguard.selectorLabels" . | nindent 4 }}
