apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.ports.exporterPort | quote }}
spec:
  selector:
    {{- include "kafka.selectorLabels" . | nindent 4 }}
  {{- if eq .Values.global.deployEnv "dev" }}
  type: NodePort
  {{- end }}
  ports:
    {{- if eq .Values.global.deployEnv "dev" }}
    - port: {{ .Values.ports.kafkaExternalPort }}
      name: kafka-external
      nodePort: {{ .Values.ports.kafkaNodePort }}
    {{- end }}
    - port: {{ .Values.ports.kafkaPort }}
      name: kafka
    - port: {{ .Values.ports.controllerPort }}
      name: controller
    - port: {{ .Values.ports.exporterPort }}
      name: exporter
