global:

  # possible environments value: dev, stage, prod
  #
  deployEnv: 'dev'

  storageRoot: '/shared-data'

  clusterSecretStoreName: 'azure-vault'
  tlsStoreName: 'tls-certificate'

  domainName: 'ivan-b.com'