variable "rg_name" {}
variable "location" {}
variable "nic" {}
variable "vm_size" {}
variable "vm_name" {}
variable "admin_public_key_path" {}
variable "admin_username" {}
variable "av_id" {}
variable "shared_disk_id" {}
variable "vm_ssh_port" {}
variable "load_balancer" {}
variable "shared_disk_count" {}