apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  ClientID: {{ .Values.clientId | b64enc | quote }}
  ClientSecret: {{ .Values.clientSecret | b64enc | quote }}