# Default values for tempo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: grafana/tempo
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.2.4"

nameOverride: ""
fullnameOverride: ""

ports:
  tempoContainer: 3200
  oltpHttpContainer: 55681
  oltpGrpcContainer: 55680

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources:
  # limits:
  #   cpu: 300m
  #   memory: 500Mi
  requests:
    cpu: 0.1
    memory: 500Mi

