apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tempo.fullname" . }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tempo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tempo.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - name: tempo-port
              containerPort: {{ .Values.ports.tempoContainer }}
            - name: otlp-grpc-port
              containerPort: {{ .Values.ports.oltpGrpcContainer }}
            - name: otlp-http-port
              containerPort: {{ .Values.ports.oltpHttpContainer }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /tmp/tempo/
      volumes:
        - name: tempo-config
          configMap:
            name: {{ include "tempo.fullname" . }}
        - name: tempo-data
          hostPath:
            path: {{ .Values.global.storageRoot }}/persist/tempo
            type: DirectoryOrCreate
