apiVersion: v1
kind: Service
metadata:
  name: {{ include "tempo.fullname" . }}
  labels:
    {{- include "tempo.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.ports.tempoContainer }}
      protocol: TCP
      name: tempo
    - port: {{ .Values.ports.oltpHttpContainer }}
      protocol: TCP
      name: oltp-http
    - port: {{ .Values.ports.oltpGrpcContainer }}
      protocol: TCP
      name: oltp-grpc
  selector:
    {{- include "tempo.selectorLabels" . | nindent 4 }}
